server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://sh-cdb-857jknxp.sql.tencentcdb.com:63232/kk_panda
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19930205Nginx*
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml



